version: '1'
services:
  storeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@tqtd6ljyl37elly3_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=Testing
      - spring.datasource.password=OracleCloud123
    restart: always